#!/bin/sh

# Normal text
text_black='\e[0;30m'
text_red='\e[0;31m'
text_green='\e[0;32m'
text_yellow='\e[0;33m'
text_blue='\e[0;34m'
text_purple='\e[0;35m'
text_cyan='\e[0;36m'
text_white='\e[0;37m'

# Bold
bold_black='\e[1;30m'
bold_red='\e[1;31m'
bold_green='\e[1;32m'
bold_yellow='\e[1;33m'
bold_blue='\e[1;34m'
bold_purple='\e[1;35m'
bold_cyan='\e[1;36m'
bold_white='\e[1;37m'

# Underline
under_black='\e[4;30m'
under_red='\e[4;31m'
under_grn='\e[4;32m'
under_yellow='\e[4;33m'
under_blue='\e[4;34m'
under_purple='\e[4;35m'
under_cyan='\e[4;36m'
under_white='\e[4;37m'

# Backgrounds
backg_black='\e[40m'
backg_red='\e[41m'
backg_green='\e[42m'
backg_yellow='\e[43m'
backg_blue='\e[44m'
backg_purple='\e[45m'
backg_cyan='\e[46m'
backg_white='\e[47m'
reset='\e[0m'
