#!/bin/sh

# Version control defaults.
export VC="${VC:-git}"
export CVS_DIFF_OPTIONS="${CVS_DIFF_OPTIONS:--up}"
export REPO_LOCATION="${REPO_LOCATION:-/home/git/}"
export VC_AUTOPUSH="${VC_AUTOPUSH:-1}"

# Shell defaults.
export EDITOR="${EDITOR:-vim}"

# Bash kit defaults.
export BASH_PROFILE="${BASH_PROFILE:-$HOME/.bash_profile}"
export BASH_KIT_ALIASES="${BASH_KIT_ALIASES:-$HOME/.bash_aliases}"

# Utility default options.
export LS_OPTIONS="${LS_OPTIONS:--G}"
export GREP_OPTIONS="${GREP_OPTIONS:---color -n}"
export ACK_OPTIONS="${ACK_OPTIONS:--a}"
export MYSQLDUMP_OPTIONS="${MYSQLDUMP_OPTIONS:---extended-insert=false --ignore-table=cache --ignore-table=cache_block --ignore-table=cache_content --ignore-table=cache_filter --ignore-table=cache_menu --ignore-table=cache_views --ignore-table=cache_views_data}"
export MYSQL_OPTIONS="${MYSQL_OPTIONS:-}"

# MySQL binaries
export MYSQL="${MYSQL:-mysql}"
export MYSQLADMIN="${MYSQLADMIN:-mysqladmin}"
export MYSQLDUMP="${MYSQLDUMP:-mysqldump}"

# SSH credentials
export SSH="${ROOT_DEV:-root@dev.fs}"

# Makefile locations
export DRUSH_MAKEFILES="${DRUSH_MAKEFILES:-$HOME/projects/makefiles/}"
